name: Create Archive
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'modpack.zip'
        exclusions: '*.git* .vscode *.ps1'
    - uses: actions/upload-artifact@v3
      with:
        name: modpack
        path: modpack.zip
