name: Create Archive
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'modpack.zip'
        exclusions: '*.git* .vscode *.ps1'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "modpack.zip"
        token: ${{ secrets.GH_TOKEN }}
